# Import dat

In [1]:
import pandas as pd
weather = pd.read_csv('./data/pydata_data.csv', sep=";")
weather.info()

<class 'pandas.DataFrame'>
RangeIndex: 67834 entries, 0 to 67833
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   STATION  67834 non-null  str
 1   NAME     67834 non-null  str
 2   DATE     67834 non-null  str
 3   PRCP     56483 non-null  float64
 4   SNWD     17540 non-null  float64
 5   TAVG     59664 non-null  float64
 6   TMAX     51147 non-null  float64
 7   TMIN     50830 non-null  float64
dtypes: float64(5), str(3)
memory usage: 4.1 MB

# Chybějicí hodnoty

In [3]:
print(weather.isnull().sum())

STATION        0
NAME           0
DATE           0
PRCP       11351
SNWD       50294
TAVG        8170
TMAX       16687
TMIN       17004
dtype: int64

In [8]:
weather_clean = weather.dropna(subset=['TAVG'])
weather_clean['PRCP'] = weather_clean['PRCP'].fillna(0)
print(weather_clean.isnull().sum())
weather.info()
print('-'*80)
weather_clean.info()

STATION        0
NAME           0
DATE           0
PRCP           0
SNWD       46963
TAVG           0
TMAX       16687
TMIN       17004
dtype: int64
<class 'pandas.DataFrame'>
RangeIndex: 67834 entries, 0 to 67833
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   STATION  67834 non-null  str
 1   NAME     67834 non-null  str
 2   DATE     67834 non-null  str
 3   PRCP     56483 non-null  float64
 4   SNWD     17540 non-null  float64
 5   TAVG     59664 non-null  float64
 6   TMAX     51147 non-null  float64
 7   TMIN     50830 non-null  float64
dtypes: float64(5), str(3)
memory usage: 4.1 MB
--------------------------------------------------------------------------------
<class 'pandas.DataFrame'>
Index: 59664 entries, 7031 to 67833
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   STATION  59664 non-null  str
 1   NAME     59664 non-null  str
 2   DATE     59664 non-null  str
 3   PRCP     59664 non-null  float64
 4   SNWD     12701 non-null  float64
 5   TAVG     59664 non-null  float64
 6   TMAX     42977 non-null  float64
 7   TMIN     42660 non-null  float64
dtypes: float64(5), str(3)
memory usage: 4.1 MB

## Změna hodnot ve sloupci

In [11]:
#print(weather_clean.head())
weather_clean['NAME'] = weather_clean['NAME'].str.title()
print(weather_clean.head())

          STATION    NAME        DATE  PRCP  SNWD  TAVG  TMAX  TMIN
7031  EZM00011518  Ruzyne  2000-01-01   0.0  30.0  -0.6   0.4  -1.7
7032  EZM00011518  Ruzyne  2000-01-02   0.0  41.0   1.0   3.1   NaN
7033  EZM00011518  Ruzyne  2000-01-03   0.0  30.0   0.1   1.1  -1.1
7034  EZM00011518  Ruzyne  2000-01-04   0.0  20.0   1.9   NaN   0.1
7035  EZM00011518  Ruzyne  2000-01-05   0.0   NaN   2.7   NaN   NaN

## Převod str na datum

In [17]:
weather_clean['DATE'] = pd.to_datetime(weather_clean['DATE'])
weather_clean.info()
print(weather_clean.head())

<class 'pandas.DataFrame'>
Index: 59664 entries, 7031 to 67833
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   STATION  59664 non-null  str
 1   NAME     59664 non-null  str
 2   DATE     59664 non-null  datetime64[us]
 3   PRCP     59664 non-null  float64
 4   SNWD     12701 non-null  float64
 5   TAVG     59664 non-null  float64
 6   TMAX     42977 non-null  float64
 7   TMIN     42660 non-null  float64
dtypes: datetime64[us](1), float64(5), str(2)
memory usage: 6.1 MB
          STATION    NAME       DATE  PRCP  SNWD  TAVG  TMAX  TMIN
7031  EZM00011518  Ruzyne 2000-01-01   0.0  30.0  -0.6   0.4  -1.7
7032  EZM00011518  Ruzyne 2000-01-02   0.0  41.0   1.0   3.1   NaN
7033  EZM00011518  Ruzyne 2000-01-03   0.0  30.0   0.1   1.1  -1.1
7034  EZM00011518  Ruzyne 2000-01-04   0.0  20.0   1.9   NaN   0.1
7035  EZM00011518  Ruzyne 2000-01-05   0.0   NaN   2.7   NaN   NaN

In [18]:
date_dic = {'date1': ['1.1.2000', '2.9.2005', '25.11.2012'],
            'date2': ['2000/1/1', '2005/9/2', '2012/11/25'],
            'date3': ['2000/1/1', '2005/2/9', '2012/25/11']}
date_df = pd.DataFrame(date_dic)
date_df.info()
print(date_df.head())

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date1   3 non-null      str
 1   date2   3 non-null      str
 2   date3   3 non-null      str
dtypes: str(3)
memory usage: 204.0 bytes
        date1       date2       date3
0    1.1.2000    2000/1/1    2000/1/1
1    2.9.2005    2005/9/2    2005/2/9
2  25.11.2012  2012/11/25  2012/25/11

### Formát data

[Přehled formátů]("https://docs.python.org/3/library/datetime.html#strftime-and-strptime-behavior")

In [28]:
date_df['date1'] = pd.to_datetime(date_df['date1'], format="%d.%m.%Y")
date_df['date2'] = pd.to_datetime(date_df['date2'])
date_df['date3'] = pd.to_datetime(date_df['date3'], format="%Y/%d/%m")
date_df.info()
print(date_df.head())

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date1   3 non-null      datetime64[us]
 1   date2   3 non-null      datetime64[us]
 2   date3   3 non-null      datetime64[us]
dtypes: datetime64[us](3)
memory usage: 204.0 bytes
       date1      date2      date3
0 2000-01-01 2000-01-01 2000-01-01
1 2005-09-02 2005-09-02 2005-09-02
2 2012-11-25 2012-11-25 2012-11-25

## Rok, měsíc a den ze sloupce DATE

In [40]:
weather_clean.info()
weather_clean.head()

<class 'pandas.DataFrame'>
Index: 59664 entries, 7031 to 67833
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   STATION     59664 non-null  str
 1   NAME        59664 non-null  str
 2   DATE        59664 non-null  datetime64[us]
 3   PRCP        59664 non-null  float64
 4   SNWD        12701 non-null  float64
 5   TAVG        59664 non-null  float64
 6   TMAX        42977 non-null  float64
 7   TMIN        42660 non-null  float64
 8   YEAR        59664 non-null  int32
 9   MONTH       59664 non-null  int32
 10  DAY         59664 non-null  int32
 11  TEMP_CLASS  59664 non-null  str
dtypes: datetime64[us](1), float64(5), int32(3), str(3)
memory usage: 7.3 MB

,STATION,NAME,DATE,PRCP,SNWD,TAVG,TMAX,TMIN,YEAR,MONTH,DAY,TEMP_CLASS
7031,EZM00011518,Ruzyne,2000-01-01,0.0,30.0,-0.6,0.4,-1.7,2000,1,1,Freeze
7032,EZM00011518,Ruzyne,2000-01-02,0.0,41.0,1.0,3.1,NaN,2000,1,2,Cold
7033,EZM00011518,Ruzyne,2000-01-03,0.0,30.0,0.1,1.1,-1.1,2000,1,3,Cold
7034,EZM00011518,Ruzyne,2000-01-04,0.0,20.0,1.9,NaN,0.1,2000,1,4,Cold
7035,EZM00011518,Ruzyne,2000-01-05,0.0,NaN,2.7,NaN,NaN,2000,1,5,Cold

In [34]:
weather_clean['YEAR'] = weather_clean['DATE'].dt.year
weather_clean['MONTH'] = weather_clean['DATE'].dt.month
weather_clean['DAY'] = weather_clean['DATE'].dt.day

## Mapování funkce na sloupec

In [39]:
#def classify_temp(temp):
#    return 'Hot' if temp > 25 else 'Cold'

def classify_temp(temp):
    if temp < -10:
        return 'Extreme freeze'
    if temp < 0:
        return 'Freeze'
    if temp < 20:
        return 'Cold'
    if temp < 30:
        return 'Hot'
    return 'Extreme hot'


weather_clean['TEMP_CLASS'] = weather_clean['TAVG'].apply(classify_temp)

## Filtrování řádků

In [43]:
weather_Ruzyne = weather_clean[weather_clean['NAME'] == 'Ruzyne']
weather_Ruzyne.info()
weather_Ruzyne.head()

<class 'pandas.DataFrame'>
Index: 7601 entries, 7031 to 14631
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   STATION     7601 non-null   str
 1   NAME        7601 non-null   str
 2   DATE        7601 non-null   datetime64[us]
 3   PRCP        7601 non-null   float64
 4   SNWD        893 non-null    float64
 5   TAVG        7601 non-null   float64
 6   TMAX        4351 non-null   float64
 7   TMIN        4493 non-null   float64
 8   YEAR        7601 non-null   int32
 9   MONTH       7601 non-null   int32
 10  DAY         7601 non-null   int32
 11  TEMP_CLASS  7601 non-null   str
dtypes: datetime64[us](1), float64(5), int32(3), str(3)
memory usage: 682.9 KB

,STATION,NAME,DATE,PRCP,SNWD,TAVG,TMAX,TMIN,YEAR,MONTH,DAY,TEMP_CLASS
7031,EZM00011518,Ruzyne,2000-01-01,0.0,30.0,-0.6,0.4,-1.7,2000,1,1,Freeze
7032,EZM00011518,Ruzyne,2000-01-02,0.0,41.0,1.0,3.1,NaN,2000,1,2,Cold
7033,EZM00011518,Ruzyne,2000-01-03,0.0,30.0,0.1,1.1,-1.1,2000,1,3,Cold
7034,EZM00011518,Ruzyne,2000-01-04,0.0,20.0,1.9,NaN,0.1,2000,1,4,Cold
7035,EZM00011518,Ruzyne,2000-01-05,0.0,NaN,2.7,NaN,NaN,2000,1,5,Cold

In [44]:
weather_Ruzyne_2000 = weather_clean[(weather_clean['NAME'] == 'Ruzyne') & (weather_clean['YEAR'] == 2000)]
weather_Ruzyne_2000.info()
weather_Ruzyne_2000.head()

<class 'pandas.DataFrame'>
Index: 366 entries, 7031 to 7396
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   STATION     366 non-null    str
 1   NAME        366 non-null    str
 2   DATE        366 non-null    datetime64[us]
 3   PRCP        366 non-null    float64
 4   SNWD        32 non-null     float64
 5   TAVG        366 non-null    float64
 6   TMAX        325 non-null    float64
 7   TMIN        244 non-null    float64
 8   YEAR        366 non-null    int32
 9   MONTH       366 non-null    int32
 10  DAY         366 non-null    int32
 11  TEMP_CLASS  366 non-null    str
dtypes: datetime64[us](1), float64(5), int32(3), str(3)
memory usage: 32.9 KB

,STATION,NAME,DATE,PRCP,SNWD,TAVG,TMAX,TMIN,YEAR,MONTH,DAY,TEMP_CLASS
7031,EZM00011518,Ruzyne,2000-01-01,0.0,30.0,-0.6,0.4,-1.7,2000,1,1,Freeze
7032,EZM00011518,Ruzyne,2000-01-02,0.0,41.0,1.0,3.1,NaN,2000,1,2,Cold
7033,EZM00011518,Ruzyne,2000-01-03,0.0,30.0,0.1,1.1,-1.1,2000,1,3,Cold
7034,EZM00011518,Ruzyne,2000-01-04,0.0,20.0,1.9,NaN,0.1,2000,1,4,Cold
7035,EZM00011518,Ruzyne,2000-01-05,0.0,NaN,2.7,NaN,NaN,2000,1,5,Cold

In [45]:
weather_TAVG_gt_20 = weather_clean[weather_clean['TAVG'] > 20]
weather_TAVG_gt_20.info()
weather_TAVG_gt_20.head()

<class 'pandas.DataFrame'>
Index: 7907 entries, 7167 to 67770
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   STATION     7907 non-null   str
 1   NAME        7907 non-null   str
 2   DATE        7907 non-null   datetime64[us]
 3   PRCP        7907 non-null   float64
 4   SNWD        1128 non-null   float64
 5   TAVG        7907 non-null   float64
 6   TMAX        5891 non-null   float64
 7   TMIN        6471 non-null   float64
 8   YEAR        7907 non-null   int32
 9   MONTH       7907 non-null   int32
 10  DAY         7907 non-null   int32
 11  TEMP_CLASS  7907 non-null   str
dtypes: datetime64[us](1), float64(5), int32(3), str(3)
memory usage: 710.4 KB

,STATION,NAME,DATE,PRCP,SNWD,TAVG,TMAX,TMIN,YEAR,MONTH,DAY,TEMP_CLASS
7167,EZM00011518,Ruzyne,2000-05-16,0.0,NaN,21.1,28.5,11.3,2000,5,16,Hot
7185,EZM00011518,Ruzyne,2000-06-03,0.0,NaN,21.4,29.0,11.6,2000,6,3,Hot
7186,EZM00011518,Ruzyne,2000-06-04,0.0,NaN,20.6,29.4,13.4,2000,6,4,Hot
7187,EZM00011518,Ruzyne,2000-06-05,0.0,NaN,21.1,28.6,14.1,2000,6,5,Hot
7192,EZM00011518,Ruzyne,2000-06-10,0.0,NaN,22.1,30.0,11.8,2000,6,10,Hot

## Výběr sloupců
### Jeden sloupec -> Series

In [46]:
tavg = weather_clean['TAVG']
tavg.info()
tavg.describe()

<class 'pandas.Series'>
Index: 59664 entries, 7031 to 67833
Series name: TAVG
Non-Null Count  Dtype
--------------  -----
59664 non-null  float64
dtypes: float64(1)
memory usage: 2.9 MB

count    59664.000000
mean        10.169048
std          8.342663
min        -21.600000
25%          3.600000
50%         10.500000
75%         16.900000
max         30.300000
Name: TAVG, dtype: float64

## Více sloupců -> DataFrame

In [48]:
weather_clean_subset = weather_clean[["DATE", "STATION", "NAME", "TAVG"]]
weather_clean_subset.info()
weather_clean_subset.head()

<class 'pandas.DataFrame'>
Index: 59664 entries, 7031 to 67833
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   DATE     59664 non-null  datetime64[us]
 1   STATION  59664 non-null  str
 2   NAME     59664 non-null  str
 3   TAVG     59664 non-null  float64
dtypes: datetime64[us](1), float64(1), str(2)
memory usage: 4.3 MB

           DATE      STATION    NAME  TAVG
7031 2000-01-01  EZM00011518  Ruzyne  -0.6
7032 2000-01-02  EZM00011518  Ruzyne   1.0
7033 2000-01-03  EZM00011518  Ruzyne   0.1
7034 2000-01-04  EZM00011518  Ruzyne   1.9
7035 2000-01-05  EZM00011518  Ruzyne   2.7

## Odtranění nepotřebných sloupců -> drop()

In [62]:
weather_clean.head()
#weather_clean.drop(['PRCP', 'TEMP_CLASS'], axis=1, inplace=True)
weather_clean.head()

          STATION    NAME       DATE  SNWD  TAVG  TMAX  TMIN  YEAR  MONTH  DAY
7031  EZM00011518  Ruzyne 2000-01-01  30.0  -0.6   0.4  -1.7  2000      1    1
7032  EZM00011518  Ruzyne 2000-01-02  41.0   1.0   3.1   NaN  2000      1    2
7033  EZM00011518  Ruzyne 2000-01-03  30.0   0.1   1.1  -1.1  2000      1    3
7034  EZM00011518  Ruzyne 2000-01-04  20.0   1.9   NaN   0.1  2000      1    4
7035  EZM00011518  Ruzyne 2000-01-05   NaN   2.7   NaN   NaN  2000      1    5

# Mazání nepotřebných objektů

In [51]:
%who

classify_temp	 date_df	 date_dic	 pd	 tavg	 weather	 weather_Ruzyne	 weather_Ruzyne_2000	 weather_TAVG_gt_20
weather_clean	 weather_clean_subset

In [50]:
weather = None
weather_Ruzyne_2000 = None

## Dynamický výběr sloupců

In [63]:
weather_numeric = weather_clean.select_dtypes(include=['number'])
weather_numeric.head()

      SNWD  TAVG  TMAX  TMIN  YEAR  MONTH  DAY
7031  30.0  -0.6   0.4  -1.7  2000      1    1
7032  41.0   1.0   3.1   NaN  2000      1    2
7033  30.0   0.1   1.1  -1.1  2000      1    3
7034  20.0   1.9   NaN   0.1  2000      1    4
7035   NaN   2.7   NaN   NaN  2000      1    5

In [65]:
temp_cols = [col for col in weather_clean.columns if col.startswith('T')]
print(temp_cols)
weather_temp = weather_clean[temp_cols]
weather_temp.head()

['TAVG', 'TMAX', 'TMIN']

      TAVG  TMAX  TMIN
7031  -0.6   0.4  -1.7
7032   1.0   3.1   NaN
7033   0.1   1.1  -1.1
7034   1.9   NaN   0.1
7035   2.7   NaN   NaN

## Konverze dat -> astype()

In [68]:
weather_clean['TEMP_CLASS'] = weather_clean['TAVG'].apply(classify_temp)
weather_clean.info()
weather_clean.head()

<class 'pandas.DataFrame'>
Index: 59664 entries, 7031 to 67833
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   STATION     59664 non-null  str
 1   NAME        59664 non-null  str
 2   DATE        59664 non-null  datetime64[us]
 3   SNWD        12701 non-null  float64
 4   TAVG        59664 non-null  float64
 5   TMAX        42977 non-null  float64
 6   TMIN        42660 non-null  float64
 7   YEAR        59664 non-null  int32
 8   MONTH       59664 non-null  int32
 9   DAY         59664 non-null  int32
 10  TEMP_CLASS  59664 non-null  str
dtypes: datetime64[us](1), float64(4), int32(3), str(3)
memory usage: 6.8 MB

,STATION,NAME,DATE,SNWD,TAVG,TMAX,TMIN,YEAR,MONTH,DAY,TEMP_CLASS
7031,EZM00011518,Ruzyne,2000-01-01,30.0,-0.6,0.4,-1.7,2000,1,1,Freeze
7032,EZM00011518,Ruzyne,2000-01-02,41.0,1.0,3.1,NaN,2000,1,2,Cold
7033,EZM00011518,Ruzyne,2000-01-03,30.0,0.1,1.1,-1.1,2000,1,3,Cold
7034,EZM00011518,Ruzyne,2000-01-04,20.0,1.9,NaN,0.1,2000,1,4,Cold
7035,EZM00011518,Ruzyne,2000-01-05,NaN,2.7,NaN,NaN,2000,1,5,Cold

Přetypování na kategorii

In [69]:
weather_clean['TEMP_CAT'] = weather_clean['TEMP_CLASS'].astype('category')
weather_clean.info()
weather_clean.head()

<class 'pandas.DataFrame'>
Index: 59664 entries, 7031 to 67833
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   STATION     59664 non-null  str
 1   NAME        59664 non-null  str
 2   DATE        59664 non-null  datetime64[us]
 3   SNWD        12701 non-null  float64
 4   TAVG        59664 non-null  float64
 5   TMAX        42977 non-null  float64
 6   TMIN        42660 non-null  float64
 7   YEAR        59664 non-null  int32
 8   MONTH       59664 non-null  int32
 9   DAY         59664 non-null  int32
 10  TEMP_CLASS  59664 non-null  str
 11  TEMP_CAT    59664 non-null  category
dtypes: category(1), datetime64[us](1), float64(4), int32(3), str(3)
memory usage: 6.9 MB

,STATION,NAME,DATE,SNWD,TAVG,TMAX,TMIN,YEAR,MONTH,DAY,TEMP_CLASS,TEMP_CAT
7031,EZM00011518,Ruzyne,2000-01-01,30.0,-0.6,0.4,-1.7,2000,1,1,Freeze,Freeze
7032,EZM00011518,Ruzyne,2000-01-02,41.0,1.0,3.1,NaN,2000,1,2,Cold,Cold
7033,EZM00011518,Ruzyne,2000-01-03,30.0,0.1,1.1,-1.1,2000,1,3,Cold,Cold
7034,EZM00011518,Ruzyne,2000-01-04,20.0,1.9,NaN,0.1,2000,1,4,Cold,Cold
7035,EZM00011518,Ruzyne,2000-01-05,NaN,2.7,NaN,NaN,2000,1,5,Cold,Cold

In [70]:
weather_clean['STATION'] = weather_clean['STATION'].astype('category')
weather_clean.info()
weather_clean.head()

<class 'pandas.DataFrame'>
Index: 59664 entries, 7031 to 67833
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   STATION     59664 non-null  category
 1   NAME        59664 non-null  str
 2   DATE        59664 non-null  datetime64[us]
 3   SNWD        12701 non-null  float64
 4   TAVG        59664 non-null  float64
 5   TMAX        42977 non-null  float64
 6   TMIN        42660 non-null  float64
 7   YEAR        59664 non-null  int32
 8   MONTH       59664 non-null  int32
 9   DAY         59664 non-null  int32
 10  TEMP_CLASS  59664 non-null  str
 11  TEMP_CAT    59664 non-null  category
dtypes: category(2), datetime64[us](1), float64(4), int32(3), str(2)
memory usage: 6.5 MB

,STATION,NAME,DATE,SNWD,TAVG,TMAX,TMIN,YEAR,MONTH,DAY,TEMP_CLASS,TEMP_CAT
7031,EZM00011518,Ruzyne,2000-01-01,30.0,-0.6,0.4,-1.7,2000,1,1,Freeze,Freeze
7032,EZM00011518,Ruzyne,2000-01-02,41.0,1.0,3.1,NaN,2000,1,2,Cold,Cold
7033,EZM00011518,Ruzyne,2000-01-03,30.0,0.1,1.1,-1.1,2000,1,3,Cold,Cold
7034,EZM00011518,Ruzyne,2000-01-04,20.0,1.9,NaN,0.1,2000,1,4,Cold,Cold
7035,EZM00011518,Ruzyne,2000-01-05,NaN,2.7,NaN,NaN,2000,1,5,Cold,Cold

## Datum

In [71]:
weather_clean['MONTH_NAME'] = weather_clean['DATE'].dt.month_name()
weather_clean.head()

,STATION,NAME,DATE,SNWD,TAVG,TMAX,TMIN,YEAR,MONTH,DAY,TEMP_CLASS,TEMP_CAT,MONTH_NAME
7031,EZM00011518,Ruzyne,2000-01-01,30.0,-0.6,0.4,-1.7,2000,1,1,Freeze,Freeze,January
7032,EZM00011518,Ruzyne,2000-01-02,41.0,1.0,3.1,NaN,2000,1,2,Cold,Cold,January
7033,EZM00011518,Ruzyne,2000-01-03,30.0,0.1,1.1,-1.1,2000,1,3,Cold,Cold,January
7034,EZM00011518,Ruzyne,2000-01-04,20.0,1.9,NaN,0.1,2000,1,4,Cold,Cold,January
7035,EZM00011518,Ruzyne,2000-01-05,NaN,2.7,NaN,NaN,2000,1,5,Cold,Cold,January

## Chyby při konverzi

In [73]:
data_dic = {'age': ['25', '30', 'třicet', '45'],
            'name': ['Adam', 'Bedřich', 'Cecilka', 'Dana']}

df = pd.DataFrame(data_dic)
df.info()
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   age     4 non-null      str
 1   name    4 non-null      str
dtypes: str(2)
memory usage: 196.0 bytes

      age     name
0      25     Adam
1      30  Bedřich
2  třicet  Cecilka
3      45     Dana

In [79]:
#df['age'] = df['age'].astype(int)
#df['age'] = pd.to_numeric(df['age'])  # ValueError: Unable to parse string "třicet"
df['age'] = pd.to_numeric(df['age'], errors='coerce')

df.info()
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   age     3 non-null      float64
 1   name    4 non-null      str
dtypes: float64(1), str(1)
memory usage: 196.0 bytes

    age     name
0  25.0     Adam
1  30.0  Bedřich
2   NaN  Cecilka
3  45.0     Dana