# Úkol 1

Načtěte soubor 'Chocolate_Sales_csv' a proveďte správnou úpravu dat.

- ✅ Načtení dat
- ✅ Odstranění nepotřebných sloupců (pokud nějaké jsou)
- ✅ Transformace na vhodné datové typy
- ✅ Řešení chybějících hodnot
- ✅ Odstranění duplicitních řádků (pokud nějaké jsou)
- ✅ Piposná statistika

## Načtení dat ✅

In [ ]:
import pandas as pd

df = pd.read_csv('./data/Chocolate_Sales.csv')

df.info()
df.head()

## Odstranění nepotřebných sloupců ✅

Zde asi není potřeba nic odstraňovat.

## Transformace na vhodné datové typy ✅

In [27]:
df.info()
df.head()

df['Date'] = pd.to_datetime(df['Date'], format="%d/%m/%Y")

df.info()
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 3282 entries, 0 to 3281
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Sales Person   3282 non-null   str
 1   Country        3282 non-null   str
 2   Product        3282 non-null   str
 3   Date           3282 non-null   str
 4   Amount         3282 non-null   str
 5   Boxes Shipped  3282 non-null   int64
dtypes: int64(1), str(5)
memory usage: 154.0 KB
<class 'pandas.DataFrame'>
RangeIndex: 3282 entries, 0 to 3281
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Sales Person   3282 non-null   str
 1   Country        3282 non-null   str
 2   Product        3282 non-null   str
 3   Date           3282 non-null   datetime64[us]
 4   Amount         3282 non-null   str
 5   Boxes Shipped  3282 non-null   int64
dtypes: datetime64[us](1), int64(1), str(4)
memory usage: 154.0 KB

,Sales Person,Country,Product,Date,Amount,Boxes Shipped
0,Jehu Rudeforth,UK,Mint Chip Choco,2022-01-04,"$5,320.00",180
1,Van Tuxwell,India,85% Dark Bars,2022-08-01,"$7,896.00",94
2,Gigi Bohling,India,Peanut Butter Cubes,2022-07-07,"$4,501.00",91
3,Jan Morforth,Australia,Peanut Butter Cubes,2022-04-27,"$12,726.00",342
4,Jehu Rudeforth,UK,Peanut Butter Cubes,2022-02-24,"$13,685.00",184

In [28]:
#def clean_amount(amount: str) -> str:
#    return amount.replace("$","").replace(",","")

df['Amount'] = df['Amount'].str.replace("$","").str.replace(",","").astype(float)

df.info()
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 3282 entries, 0 to 3281
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Sales Person   3282 non-null   str
 1   Country        3282 non-null   str
 2   Product        3282 non-null   str
 3   Date           3282 non-null   datetime64[us]
 4   Amount         3282 non-null   float64
 5   Boxes Shipped  3282 non-null   int64
dtypes: datetime64[us](1), float64(1), int64(1), str(3)
memory usage: 154.0 KB

,Sales Person,Country,Product,Date,Amount,Boxes Shipped
0,Jehu Rudeforth,UK,Mint Chip Choco,2022-01-04,5320.0,180
1,Van Tuxwell,India,85% Dark Bars,2022-08-01,7896.0,94
2,Gigi Bohling,India,Peanut Butter Cubes,2022-07-07,4501.0,91
3,Jan Morforth,Australia,Peanut Butter Cubes,2022-04-27,12726.0,342
4,Jehu Rudeforth,UK,Peanut Butter Cubes,2022-02-24,13685.0,184

In [29]:
df['Country'] = df['Country'].astype('category')

df.info()
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 3282 entries, 0 to 3281
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Sales Person   3282 non-null   str
 1   Country        3282 non-null   category
 2   Product        3282 non-null   str
 3   Date           3282 non-null   datetime64[us]
 4   Amount         3282 non-null   float64
 5   Boxes Shipped  3282 non-null   int64
dtypes: category(1), datetime64[us](1), float64(1), int64(1), str(2)
memory usage: 131.6 KB

,Sales Person,Country,Product,Date,Amount,Boxes Shipped
0,Jehu Rudeforth,UK,Mint Chip Choco,2022-01-04,5320.0,180
1,Van Tuxwell,India,85% Dark Bars,2022-08-01,7896.0,94
2,Gigi Bohling,India,Peanut Butter Cubes,2022-07-07,4501.0,91
3,Jan Morforth,Australia,Peanut Butter Cubes,2022-04-27,12726.0,342
4,Jehu Rudeforth,UK,Peanut Butter Cubes,2022-02-24,13685.0,184

In [30]:
df['Product'] = df['Product'].astype('category')

df.info()
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 3282 entries, 0 to 3281
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Sales Person   3282 non-null   str
 1   Country        3282 non-null   category
 2   Product        3282 non-null   category
 3   Date           3282 non-null   datetime64[us]
 4   Amount         3282 non-null   float64
 5   Boxes Shipped  3282 non-null   int64
dtypes: category(2), datetime64[us](1), float64(1), int64(1), str(1)
memory usage: 109.3 KB

,Sales Person,Country,Product,Date,Amount,Boxes Shipped
0,Jehu Rudeforth,UK,Mint Chip Choco,2022-01-04,5320.0,180
1,Van Tuxwell,India,85% Dark Bars,2022-08-01,7896.0,94
2,Gigi Bohling,India,Peanut Butter Cubes,2022-07-07,4501.0,91
3,Jan Morforth,Australia,Peanut Butter Cubes,2022-04-27,12726.0,342
4,Jehu Rudeforth,UK,Peanut Butter Cubes,2022-02-24,13685.0,184

## Řešení chybějících hodnot ✅

In [31]:
print(df.isnull().sum())

Sales Person     0
Country          0
Product          0
Date             0
Amount           0
Boxes Shipped    0
dtype: int64

Žádné chybějící hodnoty.

## Odstranění duplicitních řádků ✅

In [32]:
print(f"Počet duplicitních řádků: {df.duplicated().sum()}")

Počet duplicitních řádků: 0

Žádné duplicitní řídky.

## Popisná statistika

In [33]:
df.describe()

                             Date        Amount  Boxes Shipped
count                        3282   3282.000000    3282.000000
mean   2023-05-03 15:09:06.252285   6030.338775     164.666971
min           2022-01-03 00:00:00      7.000000       1.000000
25%           2022-07-04 00:00:00   2521.495000      71.000000
50%           2023-05-11 00:00:00   5225.500000     137.000000
75%           2024-03-02 00:00:00   8556.842500     232.000000
max           2024-08-31 00:00:00  26170.950000     778.000000
std                           NaN   4393.980200     124.024736

## Uložení upravených dat

In [ ]:
df.to_csv('./data/Chocolate_Sales_cleaned.csv', index=False)