# Agregace

- **Základní agregace** se provádí pomocí metod `agg()` a `aggregate()`, které umožňují aplikovat jednu nebo více agregačních funkcí současně (např. `sum()`, `mean()`, `min()`, `max()`). Tyto metody jsou flexibilní a podporují kombinování vestavěných a vlastních funkcí. Viz [agg()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.agg.html) a [aggregate()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.aggregate.html).

- **Kumulované agregace** jsou operace, které aplikují agregační funkci postupně na řadu hodnot. Mezi nejčastěji používané kumulované metody patří:
    - `cummax()`: Kumulativní maximum
    - `cummin()`: Kumulativní minimum
    - `cumsum()`: Kumulativní součet


- **Klouzavé agregace** se provádějí pomocí metody `rolling()`, která vytváří klouzavé okno o specifikované velikosti a aplikuje agregační funkce na jednotlivá okna. To je užitečné pro analýzu trendů a výpočty založené na časových řadách. Viz [rolling()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.rolling.html).

### Shlukování dat za pomoci metody `groupby()`

- Metoda `groupby()` slouží ke shlukování dat podle jednoho nebo více klíčů. Lze ji použít k výpočtu souhrnných statistik pro jednotlivé skupiny. V případě **DataFrame** můžeme shlukovat buď podle řádků (standardně `axis=0`), nebo podle sloupců (`axis=1`). Shlukování lze provádět na základě hodnot ve sloupci, na indexech nebo i na základě více klíčů. Viz [groupby()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.groupby.html).

### Transformace dat

- **Transformace řádků na sloupce a opačně** se provádí pomocí metody `transpose()`, která přehazuje řádky za sloupce a naopak. Tato operace se často používá k reorganizaci dat v **DataFrame**. Viz [transpose()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.transpose.html).

- **Transformace řádků a sloupců s unikátními hodnotami** pomocí metody `pivot()`. Tato metoda přehazuje data na základě konkrétních hodnot sloupce a vrací **DataFrame** s novými indexy a sloupci, ale nepodporuje agregaci. Je užitečná pro transformaci dat bez nutnosti jejich souhrnného zpracování. Viz [pivot()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.pivot.html).
    - Pozn.: `pivot()` nepodporuje agregace; pokud se v datech nacházejí duplicitní hodnoty, vrací chybu.

- **Transformace řádků a sloupců s agregací** pomocí metody `pivot_table()`. Tato metoda podporuje agregaci hodnot pomocí specifikovaných funkcí (např. průměr, součet) a je vhodná pro vytváření kontingenčních tabulek. Viz [pivot_table()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.pivot_table.html).
    - Příklad: `df.pivot_table(values='hodnota', index='index_sloupec', columns='sloupec', aggfunc='sum')`

In [40]:
import pandas as pd

weather = pd.read_csv('./data/pydata_data.csv', sep=";")

weather['YEAR'] = weather['DATE'].str[:4].astype(int)
weather['MONTH'] = weather['DATE'].str[5:7].astype(int)
weather['DAY'] = weather['DATE'].str[8:].astype(int)

weather['DATE'] = pd.to_datetime(weather['DATE'])
#weather['YEAR'] = weather['DATE'].dt.year
#weather['MONTH'] = weather['DATE'].dt.month
#weather['DAY'] = weather['DATE'].dt.day

weather.info()
weather.head()

<class 'pandas.DataFrame'>
RangeIndex: 67834 entries, 0 to 67833
Data columns (total 11 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   STATION  67834 non-null  str
 1   NAME     67834 non-null  str
 2   DATE     67834 non-null  datetime64[us]
 3   PRCP     56483 non-null  float64
 4   SNWD     17540 non-null  float64
 5   TAVG     59664 non-null  float64
 6   TMAX     51147 non-null  float64
 7   TMIN     50830 non-null  float64
 8   YEAR     67834 non-null  int64
 9   MONTH    67834 non-null  int64
 10  DAY      67834 non-null  int64
dtypes: datetime64[us](1), float64(5), int64(3), str(2)
memory usage: 5.7 MB

,STATION,NAME,DATE,PRCP,SNWD,TAVG,TMAX,TMIN,YEAR,MONTH,DAY
0,GME00132274,PIDING,2006-12-01,0.0,0.0,NaN,4.2,1.0,2006,12,1
1,GME00132274,PIDING,2006-12-02,0.0,0.0,NaN,1.8,-1.7,2006,12,2
2,GME00132274,PIDING,2006-12-03,0.0,0.0,NaN,5.1,-4.6,2006,12,3
3,GME00132274,PIDING,2006-12-04,19.0,0.0,NaN,8.3,-0.9,2006,12,4
4,GME00132274,PIDING,2006-12-05,0.0,0.0,NaN,12.0,0.9,2006,12,5

## Agregační funkce
### Jedna agregační funkce

In [41]:
temp_avg = weather.groupby('NAME')['TAVG'].mean()
temp_avg

NAME
GRAZ                 10.636042
KOSICE               10.146669
MOSNOV                9.551711
PIDING                     NaN
PRAHA KLEMENTINUM          NaN
PRAHA LIBUS          10.057665
RUZYNE                9.305144
SALZBURG             10.014191
TURANY               10.219039
WIEN                 11.508353
Name: TAVG, dtype: float64

### Více agregačních funkcí

In [42]:
temp_by_name = weather.groupby('NAME')['TAVG'].agg(['min', 'mean', 'median', 'max'])
temp_by_name

                    min       mean  median   max
NAME
GRAZ              -13.3  10.636042    11.2  28.4
KOSICE            -15.4  10.146669    10.7  28.8
MOSNOV            -21.6   9.551711    10.1  28.9
PIDING              NaN        NaN     NaN   NaN
PRAHA KLEMENTINUM   NaN        NaN     NaN   NaN
PRAHA LIBUS       -14.3  10.057665    10.2  30.3
RUZYNE            -16.6   9.305144     9.6  28.7
SALZBURG          -16.2  10.014191    10.3  28.6
TURANY            -17.9  10.219039    10.6  29.7
WIEN              -13.3  11.508353    11.8  30.1

### Shlukování podle více kategorií

In [43]:
temp_by_name_year = weather.groupby(['NAME', 'YEAR'])['TAVG'].agg(['min', 'mean', 'median', 'max'])
temp_by_name_year

            min       mean  median   max
NAME YEAR
GRAZ 2000  -8.8  11.331421   12.90  26.6
     2001  -9.3  10.753973   11.90  26.8
     2002  -8.9  11.133151   10.70  27.5
     2003 -13.3  10.521918   10.40  28.1
     2004  -7.0   9.865847   11.80  25.4
...         ...        ...     ...   ...
WIEN 2016  -6.5  11.595628   11.05  27.7
     2017  -7.3  11.715890   11.70  29.5
     2018  -9.6  12.667787   14.20  27.8
     2019  -5.7  12.555890   11.90  29.1
     2020  -2.2  13.073065   13.50  26.1

[189 rows x 4 columns]

## Pokročilá agregace
Různé agregační funkce pro různé sloupce.

In [44]:
weather_agg = weather.groupby(['NAME', 'YEAR']).agg({'TMIN': 'min',
                                                     'TMAX': 'max',
                                                     'TAVG': 'mean',
                                                     'PRCP': 'sum',
                                                     'STATION': 'nunique'})

weather_agg

           TMIN  TMAX       TAVG   PRCP  STATION
NAME YEAR
GRAZ 2000 -13.2  35.5  11.331421  755.3        1
     2001 -12.8  33.6  10.753973  534.3        1
     2002 -13.0  35.2  11.133151  872.1        1
     2003 -17.4  36.6  10.521918  660.8        1
     2004 -11.7  33.6   9.865847  899.5        1
...         ...   ...        ...    ...      ...
WIEN 2016  -9.6  33.7  11.595628  599.5        1
     2017 -12.6  38.4  11.715890  468.8        1
     2018 -12.4  35.2  12.667787  475.7        1
     2019  -8.2  37.0  12.555890  490.7        1
     2020  -4.7  35.9  13.073065  499.3        1

[189 rows x 5 columns]

### pivot_table()

In [45]:
weather_prcp = weather.pivot_table(values='PRCP',
                                   index='NAME',
                                   columns='YEAR',
                                   aggfunc='mean',
                                   dropna=True,
                                   fill_value='NA')

weather_prcp

C:\Users\Student\AppData\Local\Temp\ipykernel_10304\1041317828.py:1: Pandas4Warning: Using a fill_value that cannot be held in the existing dtype is deprecated and will raise in a future version.
  weather_prcp = weather.pivot_table(values='PRCP',

YEAR,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
NAME,,,,,,,,,,,,,,,,,,,,,
GRAZ,2.063661,2.283333,5.012069,4.263226,4.915301,2.438356,2.066027,2.26411,2.597268,3.299452,...,9.361224,10.845614,7.118681,9.768478,12.601667,10.187273,10.011538,5.911538,9.024658,9.695385
KOSICE,1.450273,1.551781,1.776438,1.347671,1.764481,1.921096,1.78274,1.728493,1.762842,1.679726,...,1.43589,1.499727,1.688493,1.914835,1.574118,2.021154,1.519231,2.232659,3.808587,4.500971
MOSNOV,1.853506,2.29562,1.611502,1.240055,1.426741,1.768681,1.507418,1.947253,1.908767,1.951923,...,1.680112,1.642857,1.592603,2.048493,1.225872,1.757377,2.056438,1.447339,1.789315,3.120433
PIDING,NA,NA,NA,NA,NA,NA,1.154839,3.77863,3.114208,3.747397,...,3.022192,3.430874,3.368493,3.232877,2.701096,3.751913,3.697808,3.322466,3.690137,4.503607
PRAHA KLEMENTINUM,1.054372,1.512329,1.812329,0.731781,1.077049,0.671667,NA,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
PRAHA LIBUS,0.699145,1.155417,2.397386,0.768524,1.1825,1.300567,1.393315,1.461236,1.388202,1.426389,...,2.208832,3.039444,2.247383,1.823014,1.248795,1.59478,3.430362,1.29233,1.850416,1.89195
RUZYNE,1.377043,1.842435,1.970684,0.81662,1.300275,1.327824,1.32967,1.387293,1.327869,1.302192,...,1.266295,1.430601,1.84137,1.712329,1.071637,1.306371,3.974011,1.299415,1.867318,1.725868
SALZBURG,3.184973,4.218345,6.392627,4.788945,4.952838,3.327123,3.003836,3.20411,2.915574,3.839178,...,8.086916,6.758779,8.51875,9.861654,9.859836,13.51,11.982836,17.186364,7.609091,8.6
TURANY,1.557308,1.90922,1.584211,1.298017,1.238504,1.575068,1.791758,1.320661,1.169126,1.528219,...,1.072253,1.148634,1.580822,1.649315,1.146356,1.703039,4.920231,1.501471,1.829379,1.932278
WIEN,1.468579,1.721545,3.85545,2.268528,2.893043,1.631233,1.898904,2.365205,1.828689,2.464658,...,4.598824,4.495327,4.843089,6.34,4.208247,6.117347,4.596078,5.467816,5.333696,6.484416

In [46]:
weather_prcp = weather.pivot_table(values=['PRCP', 'TAVG'],
                                   index=['NAME', 'YEAR'],
                                   #columns='YEAR',
                                   aggfunc=['mean', 'min', 'max'],
                                   dropna=True,
                                   fill_value='NA')

weather_prcp

               mean             min         max
               PRCP       TAVG PRCP  TAVG  PRCP  TAVG
NAME YEAR
GRAZ 2000  2.063661  11.331421  0.0  -8.8  40.0  26.6
     2001  2.283333  10.753973  0.0  -9.3  32.8  26.8
     2002  5.012069  11.133151  0.0  -8.9  70.9  27.5
     2003  4.263226  10.521918  0.0 -13.3  42.8  28.1
     2004  4.915301   9.865847  0.0  -7.0  30.4  25.4
...             ...        ...  ...   ...   ...   ...
WIEN 2016  6.117347  11.595628  0.0  -6.5  54.1  27.7
     2017  4.596078   11.71589  0.0  -7.3  43.9  29.5
     2018  5.467816  12.667787  0.0  -9.6  48.0  27.8
     2019  5.333696   12.55589  0.0  -5.7  34.0  29.1
     2020  6.484416  13.073065  0.0  -2.2  38.1  26.1

[189 rows x 6 columns]